{% set version = "1.0.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-ggplot.multistats
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggplot.multistats_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggplot.multistats/ggplot.multistats_{{ version }}.tar.gz
  sha256: fc4a042bf7d86641e50338ba851056dc2ed1f501092f9b78ac5cf3d6ce7ece5d

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-ggplot2
    - r-hexbin
    - r-rlang
    - r-scales
  run:
    - r-base
    - r-ggplot2
    - r-hexbin
    - r-rlang
    - r-scales

test:
  commands:
    - $R -e "library('ggplot.multistats')"           # [not win]
    - "\"%R%\" -e \"library('ggplot.multistats')\""  # [win]

about:
  home: https://github.com/flying-sheep/ggplot.multistats
  license: GPL-3.0-only
  summary: Provides the ggplot binning layer stat_summaries_hex(), which functions similar to its singular form, but allows the use of multiple statistics per bin. Those statistics can be mapped to multiple bin aesthetics.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: ggplot.multistats
# Title: Multiple Summary Statistics for Binned Stats/Geometries
# Version: 1.0.0
# Authors@R: person(given = "Philipp", family = "Angerer", role = c("aut", "cre"), email = "phil.angerer@gmail.com", comment = c(ORCID = "0000-0002-0369-2888"))
# Description: Provides the ggplot binning layer stat_summaries_hex(), which functions similar to its singular form, but allows the use of multiple statistics per bin. Those statistics can be mapped to multiple bin aesthetics.
# URL: https://github.com/flying-sheep/ggplot.multistats
# BugReports: https://github.com/flying-sheep/ggplot.multistats/issues
# License: GPL-3
# Encoding: UTF-8
# LazyData: true
# Imports: methods, rlang, scales, hexbin, ggplot2
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-10-22 15:28:56 UTC; angerer
# Author: Philipp Angerer [aut, cre] (<https://orcid.org/0000-0002-0369-2888>)
# Maintainer: Philipp Angerer <phil.angerer@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-10-28 13:50:05 UTC
